### ISSUE TITLE
Runtime error on load

### ISSUE THREAD

**Issue by Mcdougall1** [xurion/ffxi-empy-pop-tracker#1] opened 2019-06-09 14:12 UTC
When i run the lua it says empryeantracker: lua runtime error: empreantracker/empyreantracker.lua:123: "pops" is not defined for strings. 

any help? please ty.

**Comment by xurion** [comment] 2020-01-03 10:58
Sorry I didn't see this the entire time :(

This is still being built - I didn't add anything to it for a little while but I'm picking it back up now.

Hopefully I'll fix the issue you raised as part of the remaining work, but I'll keep this issue open until then so I can revalidate it.

Thanks for raising!

**Comment by xurion** [comment] 2020-01-07 23:38
I have now pushed significant changes to the project that I'm hoping will fix the issue. More changes are coming and this is not considered complete yet. However could you try and reproduce the issue?

**Comment by xurion** [comment] 2020-01-10 08:44
Closing as I'm unable to reproduce this issue.

**Closed as completed** 2020-01-10 08:44 UTC
Labels: unable to reproduce
