### ISSUE TITLE
No longer tracking?

### ISSUE THREAD

**Issue by Headtatt** [xurion/ffxi-empy-pop-tracker#3] opened 2020-02-21 15:48 UTC
Within the last 48 hours tracking just doesn't seem to function.  

For example - my Orthrus tracking is showing all red, but I am looking right at the Tiger King Hide in my inventory.  

I checked that the item id has not changed (and both the resource file and the NM file match #3232) so I'm not sure what else it could be.

**Comment by xurion** [comment] 2020-02-22 17:01
Thanks for raising the issue!

Do you use the Windower distribution or a copy from this repository?

**Comment by Headtatt** [comment] 2020-02-22 17:19
... you know what IDK. I'll double check, reinstall if needed from the repository and try again.

**Comment by xurion** [comment] 2020-02-22 17:29
I ask mainly because I think the Windower one has some pieces that this one hasn't had merged to master yet.

I'll double check the changes I had in a branch that I used to get it ready for the Windower team.

**Comment by Headtatt** [comment] 2020-02-22 17:36
I did have to disable EPT in my windower profile, so it was probably that
distribution yes. I have installed the one from this repository and will
test a drop or two today to confirm if it is working as intended.

**Comment by Headtatt** [comment] 2020-02-22 18:14
Ok, quick test in Abby-Altepa the tracker did update correctly when a
San-Caked Fang dropped now that I am running this version of the code.
(thank you)

I guess that means the latest windower push has an issue, and if I wasn't
paying attention to when it updated in the background that would also
explain why the problem seemed to show up out of nowhere.

**Comment by xurion** [comment] 2020-02-22 19:08
Nice, thanks for checking. I'll double check the Windower version myself just to be sure. I've merged the branches in this repository so that should be all up to date.

**Comment by xurion** [comment] 2020-02-22 20:28
I've tested this repository as well as the Windower version and both seem ok. Not really sure what lead to that issue. Going to mark this as unable to reproduce and close for now. Thanks for the help and let me know if you see this issue again.

**Closed as completed by xurion** 2020-02-22 20:28 UTC
Labels: bug, unable to reproduce
